<?php

namespace Dashify\DashifyBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('dashify');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->scalarNode('title')
                    ->defaultValue('Dashify Admin')
                ->end()
                ->scalarNode('logo')
                    ->defaultValue(null)
                ->end()
                ->arrayNode('menu')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('label')
                                ->isRequired()
                                ->cannotBeEmpty()
                            ->end()
                            ->scalarNode('icon')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('route')
                                ->defaultNull()
                            ->end()
                            ->arrayNode('items')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('label')
                                            ->isRequired()
                                            ->cannotBeEmpty()
                                        ->end()
                                        ->scalarNode('icon')
                                            ->defaultNull()
                                        ->end()
                                        ->scalarNode('route')
                                            ->isRequired()
                                            ->cannotBeEmpty()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('ui')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('theme')
                            ->defaultValue('light')
                        ->end()
                        ->scalarNode('primary_color')
                            ->defaultValue('#4f46e5')
                        ->end()
                        ->booleanNode('dark_mode')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enable_login')
                            ->defaultTrue()
                        ->end()
                        ->scalarNode('login_route')
                            ->defaultValue('dashify_login')
                        ->end()
                        ->scalarNode('logout_route')
                            ->defaultValue('dashify_logout')
                        ->end()
                        ->scalarNode('login_redirect_route')
                            ->defaultValue('dashify_dashboard')
                        ->end()
                        ->scalarNode('logout_redirect_route')
                            ->defaultValue('dashify_login')
                        ->end()
                        ->scalarNode('user_provider')
                            ->defaultValue('app.user_provider')
                        ->end()
                        ->scalarNode('password_hasher')
                            ->defaultValue('auto')
                        ->end()
                        ->scalarNode('user_class')
                            ->defaultValue('App\Entity\User')
                        ->end()
                        ->scalarNode('user_identifier_property')
                            ->defaultValue('email')
                        ->end()
                        ->booleanNode('remember_me')
                            ->defaultTrue()
                        ->end()
                        ->integerNode('session_lifetime')
                            ->defaultValue(3600)
                        ->end()
                        ->arrayNode('roles')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('view')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['ROLE_DASHIFY_USER'])
                                ->end()
                                ->arrayNode('create')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['ROLE_DASHIFY_ADMIN'])
                                ->end()
                                ->arrayNode('edit')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['ROLE_DASHIFY_ADMIN'])
                                ->end()
                                ->arrayNode('delete')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['ROLE_DASHIFY_ADMIN'])
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
} 