dashify:
    title: 'Dashify Admin'
    logo: null
    menu:
        dashboard:
            label: 'Dashboard'
            icon: 'dashboard'
            route: 'dashify_dashboard'
        administration:
            label: 'Administration'
            icon: 'users'
            items:
                - label: 'Utilisateurs'
                  icon: 'user'
                  route: 'dashify_users'
                - label: 'Rôles'
                  icon: 'shield'
                  route: 'dashify_roles'
        settings:
            label: 'Paramètres'
            icon: 'cog'
            items:
                - label: 'Général'
                  icon: 'cog'
                  route: 'dashify_settings'
                - label: 'Sécurité'
                  icon: 'shield-check'
                  route: 'dashify_security_settings'
    ui:
        theme: 'light'
        primary_color: '#4f46e5'
        dark_mode: true
    security:
        enable_login: true
        login_route: dashify_login
        logout_route: dashify_logout
        login_redirect_route: dashify_dashboard
        logout_redirect_route: dashify_login
        user_provider: app.user_provider
        password_hasher: auto
        user_class: App\Entity\User
        user_identifier_property: email
        remember_me: true
        session_lifetime: 3600
        roles:
            view: ['ROLE_DASHIFY_USER']
            create: ['ROLE_DASHIFY_ADMIN']
            edit: ['ROLE_DASHIFY_ADMIN']
            delete: ['ROLE_DASHIFY_ADMIN']

# Configuration Twig pour les templates Dashify
twig:
    paths:
        '%kernel.project_dir%/templates': Dashify 