security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        dashify_users:
            entity:
                class: '%dashify.user.class%'
                property: '%dashify.user.identifier_property%'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        dashify_admin:
            pattern: ^/admin
            lazy: true
            provider: dashify_users
            custom_authenticator: Dashify\DashifyBundle\Security\DashifyAuthenticator
            entry_point: Dashify\DashifyBundle\Security\DashifyAuthenticator
            logout:
                path: dashify_logout
                target: dashify_login
                clear_site_data: ['*']
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /admin
                always_remember_me: true

    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN } 